# -*- coding: utf-8 -*-
"""Fursuit-лиды: слияние направления A (каталоги/getfursu.it/FursuitReview/Boosty),
направления C (orgs.biz) и собственного сбора. Дедуплицировано."""
D = "2026-09-15"
M = {"cat":"Категория","name":"Название мастерской / имя мастера","nick":"Никнейм","city":"Город",
     "reg":"Регион","makes":"Что производит","proof":"Признаки собственного производства",
     "act":"Активность","last":"Последняя обнаруженная активность","how":"Основной способ связи",
     "main":"Основной контакт","vk":"VK","tg":"Telegram","ig":"Instagram / другая соцсеть",
     "site":"Сайт","email":"Email","extra":"Дополнительные контакты","src":"Основной источник",
     "src2":"Дополнительный источник","why":"Почему подходит нашей мастерской",
     "parts":"Потенциально интересующие детали / услуги","rel":"Коммерческая релевантность 1-5",
     "q":"Качество лида A/B/C","note":"Комментарий исследователя"}
def L(**k):
    r = {"Дата проверки": D}
    for a,b in M.items(): r[b] = k.get(a,"")
    return r

FRU  = "https://fursuit.ru/i-want-fursuit/fursuit-makers-list"
PARTS = "Основы голов, глаза, зубы, клыки, когти, крепления, шарниры, декоративные детали"
PARTS_HARD = "Основы/каркасы голов, подвижные челюсти и шарниры, зубы и клыки, детали глаз, когти, крепления, мелкосерийные повторяемые детали"

FURSUIT = [
# ---------- A-уровень: производство + свежая активность ----------
L(cat="Fursuit studio", name="CofferretCraft (TakahiroReta)", nick="cofferret_craft / TakahiroReta / kot_uzumaki",
  city="Москва / Ярославль", reg="Москва",
  makes="Фурсьюты кемоно и мультяшного стиля (head, mini partial, partial, fullsuit); 3D-ПЕЧАТНЫЕ ОСНОВЫ для самостоятельного крафта (PETG, PLA, TPU); тематический мерч",
  proof="Собственный интернет-магазин с прайсом и правилами, портфолио по годам, очередь заказов, опубликованные отзывы, указаны конкретные виды пластика, две офлайн-точки («Ушастая полка» Москва, «Шиба полки» Ярославль), работает с 2022",
  act="Активна", last="2026-09 — магазин работает, очередь заказов действующая",
  how="Telegram", main="https://t.me/cofferretcraft",
  vk="https://vk.com/cofferretcraft", tg="https://t.me/cofferretcraft",
  ig="https://instagram.com/cofferret_craft", site="https://cofferret.store/", email="takahiroreta@gmail.com",
  extra="VK личный: https://vk.com/kot_uzumaki; TG личный: https://t.me/TakahiroReta; FA: takahiroreta; Twitter: @CFerretCraft; The Dealers Den: takahiroreta",
  src="https://cofferret.store/", src2="https://fursuitreview.com/m/cofferret-craft/",
  why="Уже печатает и ПРОДАЁТ 3D-основы, публично называя материалы (PETG/PLA/TPU). Это не холодный контакт, а действующий участник того же рынка: продавать можно расширение мощности, сложные детали вне возможностей своего парка и мелкосерийные тиражи под её очередь заказов.",
  parts=PARTS_HARD+", мастер-модели, тиражирование основ",
  rel=5, q="A",
  note="Сильнейший лид базы. Дедуп: kot_uzumaki = cofferretcraft = takahiroreta = TakahiroReta — одно лицо, 8 площадок сведены в одну запись. Email опубликован ею самой на сайте как контакт."),

L(cat="Private fursuit maker", name="Morgan", nick="MRGNW17 / morgan_tgk",
  city="Москва", reg="Москва",
  makes="Полный спектр: фулсьюты, головы, боди, лапы, ступни, хвосты; АНИМАТРОНИКА, LED-глаза, подвижные челюсти, съёмные рога",
  proof="Карточка мейкера в международной базе getfursu.it, заполненная и обновляемая самим мастером; заявлены премейды и стандартные коммишены, схема оплаты 50/50, собственный Telegram-канал",
  act="Активна", last="2025-03-30 — карточка обновлена самим мейкером",
  how="Telegram", main="https://t.me/morgan_tgk", vk="", tg="https://t.me/morgan_tgk",
  ig="https://www.tiktok.com/@morgan_.102", site="", email="",
  extra="", src="https://getfursu.it/c/MRGNW17", src2="https://t.me/morgan_tgk",
  why="Аниматроника, LED-глаза, подвижные челюсти и съёмные рога — это ровно те узлы, которые печатаются и точатся, а не шьются. Молодая студия (с 2023), активно наращивающая технологии: наиболее восприимчива к аутсорсу механики.",
  parts="Механические элементы и шарниры челюстей, корпуса аниматроники, детали глаз, съёмные рога, крепления",
  rel=5, q="A",
  note="Самый свежий из российских мейкеров в getfursu.it. Прямой Telegram — лучший канал входа."),

L(cat="Fursuit studio", name="ArvinsLair (Studio Fursuit Vici)", nick="ARVNSLR / Arvin Pol / arvin69",
  city="Москва", reg="Москва",
  makes="Полный спектр: фулсьюты дигитигрейд/плантиград, головы, боди, лапы, ступни, хвосты; силиконовые шрамы, LED-глаза, подвижные челюсти",
  proof="Прямая цитата студии: «Our Studio is a married couple. Fursuit is the main job» — фурсьюты как основная работа; публичная доска очереди заказов в Trello, собственный сайт со статусом коммишенов, премейды на The Dealers Den",
  act="Активна", last="2026-09-15 — статус коммишенов отслеживается автоматически по arvinslair.com/commissions.html",
  how="Сайт", main="http://arvinslair.com/", vk="https://vk.com/club68485737", tg="",
  ig="https://www.instagram.com/arvinslair/", site="http://arvinslair.com/", email="",
  extra="FA: https://www.furaffinity.net/user/arvin69/; Linktree: https://linktr.ee/arvinslair; Trello-очередь: https://trello.com/b/jmC5kLXr/arvinslair-fursuits",
  src="https://getfursu.it/c/ARVNSLR", src2="https://fursuitreview.com/m/arvins-lair/",
  why="Один из крупнейших действующих производителей РФ, для которого фурсьюты — основной заработок, а не хобби. Публичная очередь в Trello показывает поток заказов, оправдывающий закупку повторяемых деталей партиями. Принимает оплату в рублях.",
  parts=PARTS_HARD, rel=4, q="A",
  note="Дедуп: «Arvin Pol» из каталога fursuit.ru и ARVNSLR из getfursu.it — один лид. Публичный Trello — редкая возможность оценить реальную загрузку до контакта."),

L(cat="Fursuit studio", name="KrafiCat / TETRIS workshop", nick="KRAFICA / Krafi / CatKrafi",
  city="Ярославль", reg="Ярославская область",
  makes="Головы, мини-партиалы, партиалы, полные дигитигрейды, лапы, ступни, хвосты; LED-глаза, светодиоды, съёмные рога",
  proof="Собственный магазин на Etsy (TETRISworkshop) и на The Dealers Den, отзывы на FursuitReview, планы рассрочки до 4 месяцев — признаки поставленной коммерции, а не разовых работ",
  act="Активна", last="2026-09-15 — Boosty-страница активна, Instagram отслеживается автоматически",
  how="Telegram", main="https://t.me/KrafiCat", vk="https://vk.com/kartiki", tg="https://t.me/KrafiCat",
  ig="https://www.instagram.com/kraficat/", site="https://kraficat.carrd.co/", email="",
  extra="FA: https://www.furaffinity.net/user/krafi/; DeviantArt: kraficat; Etsy: https://www.etsy.com/shop/TETRISworkshop; Boosty: https://boosty.to/kraficat",
  src="https://getfursu.it/c/KRAFICA", src2="https://fursuitreview.com/m/kraficat/",
  why="Один из самых «рыночных» русских мейкеров: Etsy + DealersDen + Boosty = привычка работать с внешними поставщиками и платными сервисами. LED-глаза и съёмные рога — печатные узлы. Продаёт отдельные части, значит мыслит номенклатурой, а не только костюмами целиком.",
  parts="Детали глаз и корпуса LED-глаз, съёмные рога и антлеры, зубы, когти, крепления, основы голов",
  rel=4, q="A",
  note="Дедуп: «Krafi (TETRIS workshop)» из fursuit.ru = KRAFICA из getfursu.it = kraficat. Город Ярославль уточнён по getfursu.it — в fursuit.ru не был указан."),

L(cat="Fursuit studio", name="Crafts fur Raptors (ранее Dragon Wolf studio) / Samira", nick="CRAFURR / SamiraRedHusky / lygaryk",
  city="Минусинск / Красноярск", reg="Красноярский край",
  makes="Максимально широкий спектр: все стили (реализм, кемоно, кигуруми, тууни), все части — головы, боди, лапы, ступни, хвосты, фулсьюты; LED, вентиляторы, подвижные челюсти",
  proof="Магазин на The Dealers Den, Boosty для приёма оплат, портфолио на FurAffinity и в Instagram, карточка getfursu.it обновляется самим мейкером; работает с июня 2007",
  act="Активна", last="2024-08-12 — карточка обновлена самим мейкером",
  how="Instagram", main="https://www.instagram.com/crafts_fur_raptors/",
  vk="https://vk.com/suit_of_samira", tg="", ig="https://www.instagram.com/crafts_fur_raptors/",
  site="https://boosty.to/craftsfurraptors", email="Lygaryk@gmail.com",
  extra="FA: https://www.furaffinity.net/user/samiraredhusky1/; Twitter: https://twitter.com/lygaryk; The Dealers Den: https://www.thedealersden.com/store/crafts-fur-raptors",
  src="https://getfursu.it/c/CRAFURR", src2="https://fursuitreview.com/m/crafts-fur-raptors/",
  why="Старейший действующий русский мейкер (с 2007) с самым широким ассортиментом частей и фич. Рапторы и драконы — максимум жёстких деталей: зубы, клыки, когти, подвижные челюсти. Стаж 18 лет означает отлаженный процесс, куда легко встроить внешнего поставщика деталей.",
  parts="Зубы, клыки, когти, детали глаз, подвижные челюсти и шарниры, крепления, мастер-модели",
  rel=4, q="A",
  note="КЛЮЧЕВАЯ ДЕДУПЛИКАЦИЯ: Twitter-ник lygaryk связывает карточку «Crafts Fur Raptors» (FursuitReview/getfursu.it) с email Lygaryk@gmail.com мастера «Samira» (Красноярск) из fursuit.ru. Три разных каталога описывали одного человека. Город уточнён: Минусинск (в fursuit.ru был указан Красноярск)."),

L(cat="Fursuit studio", name="Ugolek Fursuit Studio / NAVY_WORKSHOP", nick="UgolekF / UshGalesh / ugolek_fursuitstudio",
  city="не указан", reg="не указан",
  makes="Фурсьюты и партиалы (подтверждённый партиал «канадская рысь»)",
  proof="Отзывы на FursuitReview за 2018, 2019, 2021, 2022, 2023 и 2024 — непрерывный поток заказов шесть лет подряд; собственное VK-сообщество студии; Twitter-профиль с объявлением о наборе заказов",
  act="Активна", last="2024 — отзывы клиентов; Twitter: «commissions open in September»",
  how="VK", main="https://vk.com/ugoleksuits", vk="https://vk.com/ugoleksuits", tg="",
  ig="https://www.instagram.com/ugolek_fursuitstudio/", site="", email="",
  extra="Twitter/X: https://x.com/UgolekF; FurAffinity: UshGalesh",
  src="https://fursuitreview.com/m/ugolek-fursuit-studio/", src2=FRU,
  why="Единственный в базе с документированной шестилетней непрерывной историей отзывов. Стабильный многолетний поток заказов — самый надёжный индикатор регулярной потребности в комплектующих.",
  parts=PARTS, rel=4, q="A",
  note="Дедуп: «Ugolek (UshGalesh)» из fursuit.ru = UgolekF = NAVY_WORKSHOP. Город ни в одном источнике не указан — стоит уточнить при контакте."),

L(cat="Private fursuit maker", name="FurryYana", nick="furry_yana / furryyana",
  city="не указан", reg="не указан",
  makes="Головы, партиалы, ладони-лапы в тууни-стиле",
  proof="Подтверждённый положительный отзыв клиента на FursuitReview с деталями сделки: срок 1-3 месяца, цена $501-999, оплата единым платежом",
  act="Активна", last="2025-11-17 — положительный отзыв на FursuitReview",
  how="Telegram", main="https://t.me/furryyana", vk="", tg="https://t.me/furryyana",
  ig="https://www.instagram.com/furry_yana/", site="", email="",
  extra="", src="https://fursuitreview.com/m/furryyana/", src2="https://fursuitreview.com/shiporigin/russia/",
  why="Свежий (конец 2025) положительный отзыв и срок исполнения 1-3 месяца — признак отлаженного, быстрого процесса. Быстрые мейкеры чаще других закупают готовые компоненты, вместо того чтобы лепить каждую деталь вручную.",
  parts=PARTS, rel=4, q="A",
  note="Самый свежий подтверждённый отзыв во всей выборке. Короткий срок сдачи — хороший аргумент в пользу покупных деталей."),

L(cat="Fursuit studio", name="ФурриСтудио / The Furry Studio (Bast)", nick="furrystudio / rusfurry / ElliFox",
  city="Москва", reg="Москва",
  makes="Фурсьюты «под ключ» по фурсоне заказчика: полные костюмы, головы, лапы, хвосты; кигуруми, антро-плюш, бейджи",
  proof="Собственный многоязычный сайт с формой заказа, юридический адрес (Москва, 109146), отдельный PR-менеджер, Boosty для приёма оплат, галерея работ и описание техпроцесса; студия основана осенью 2013 под Русфуренцию 2014",
  act="Активна", last="2026-09 — сайт и контактная страница актуальны",
  how="Telegram", main="https://t.me/ElliFox", vk="https://vk.com/rusfurry", tg="https://t.me/ElliFox",
  ig="https://instagram.com/furrystudio", site="https://thefurrystudio.com/", email="",
  extra="VK Bast: https://vk.com/id12960089; Twitter: twitter.com/furrystudio; FA: furrystudio; YouTube: FurryStudio; Boosty: https://boosty.to/furrystudio; второй домен: http://furry-studio.com",
  src="https://thefurrystudio.com/kontakty", src2=FRU,
  why="Крупнейшая по масштабу российская студия с формальной структурой — юрадрес, PR-менеджер, многоязычный сайт. Единственный лид, с которым можно вести переговоры как с организацией, а не с частным мастером: это открывает рамочный договор и регулярные поставки, а не разовые заказы.",
  parts=PARTS_HARD, rel=5, q="A",
  note="Дедуп: Bast / Furry Studio / rusfurry / thefurrystudio — одна студия, в каталогах фигурировала как три разные записи. Email на сайте скрыт антиспамом, поэтому не выписан — контакт через Telegram PR-менеджера."),

L(cat="Fursuit studio", name="FurR.CluB", nick="FURCLUB / SpaceAlienFox / Prisheliss",
  city="Иркутск", reg="Иркутская область",
  makes="Дигитигрейд-фулсьюты с ПОДВИЖНОЙ ЧЕЛЮСТЬЮ; головы, боди, лапы, хвосты, ступни — отдельно",
  proof="Подробно описанная собственная технология (голова без поролона, полностью стирается, универсальный крой под разные размеры), собственный сайт с прайсом и правилами, страница на Boosty; работает с июня 2013",
  act="Активна", last="2026-09-15 — карточка getfursu.it актуальна, Boosty-страница активна",
  how="Сайт", main="http://furr.club/", vk="https://vk.com/furr.club", tg="",
  ig="https://www.instagram.com/furr.club/", site="http://furr.club/", email="spacealienfox@gmail.com",
  extra="Прайс: http://furr.club/en/price.html; FA: https://www.furaffinity.net/user/furr.club/; Twitter: https://twitter.com/spacealienfox; Boosty: https://boosty.to/furr.club",
  src="https://getfursu.it/c/FURCLUB", src2=FRU,
  why="Делает жёсткие каркасные головы БЕЗ поролона и с подвижной челюстью — конструктивно самый близкий к 3D-печати подход во всей базе. Каркас, шарнир челюсти и крепления у такой технологии напрашиваются на печать. Работают 12 лет, продают части отдельно.",
  parts="Жёсткие каркасы/основы голов, шарниры и механизмы подвижной челюсти, зубы, детали глаз, крепления",
  rel=5, q="A",
  note="ВАЖНАЯ ПОПРАВКА: в каталоге fursuit.ru помечены как «заказы временно не принимаются», но карточка getfursu.it и Boosty актуальны на 2026 — студия действующая. Город Иркутск уточнён по getfursu.it. Email опубликован ими самими как контакт для заказов."),

# ---------- Приоритет по 3D-печати, но активность требует подтверждения ----------
L(cat="Fursuit parts maker", name="WesternVibe Saloon (MadWolf Studios)", nick="VVVWVVV / kavaynu / wv_saloon",
  city="Санкт-Петербург", reg="Санкт-Петербург",
  makes="Головы и мини-партиалы; ПРЯМО ЗАЯВЛЕНО: «I make fursuit foam or 3D-print bases also» — делает и продаёт поролоновые И 3D-ПЕЧАТНЫЕ ОСНОВЫ",
  proof="Детальная схема поэтапной оплаты (2/10/10/39/39%), отзывы на FursuitReview, собственная галерея мейкера на Furtrack с фото сданных костюмов",
  act="Не подтверждена (профиль активен, дата последней работы неизвестна)",
  last="2021-03-28 — последнее самообновление карточки getfursu.it; профиль на FursuitReview числится активным",
  how="Instagram", main="https://www.instagram.com/western_vibe_saloon/", vk="", tg="",
  ig="https://www.instagram.com/western_vibe_saloon/", site="", email="",
  extra="FA: https://www.furaffinity.net/user/kavaynu/; Furtrack: https://www.furtrack.com/index/maker:wv_saloon",
  src="https://getfursu.it/c/VVVWVVV", src2="https://fursuitreview.com/m/westernvibe-saloon/",
  why="Единственный в базе, кто ПРЯМО заявляет изготовление 3D-печатных основ на продажу. Значит, спрос на печатные основы в РФ он уже подтвердил собственной практикой — это либо клиент на аутсорс тиража, либо партнёр по загрузке мощностей, либо ближайший конкурент, которого важно знать.",
  parts="Основы голов (3D-печать и поролон), мастер-модели, тиражирование, крепления",
  rel=5, q="B",
  note="ПРИОРИТЕТНЫЙ по профилю, но понижен до B: карточка не обновлялась с 2021, прямых мессенджеров нет — только Instagram, недоступный для проверки. Дедуп: VVVWVVV = kavaynu = wv_saloon = MadWolf Studios."),

L(cat="Fursuit parts maker", name="Hikarinaka (DKAG / Dolls Kingdom)", nick="Hikarinaka / WindLighter",
  city="Санкт-Петербург", reg="Санкт-Петербург",
  makes="Кигуруми/анимегао маски, BJD, а также БОЛВАНКИ (blanks) и ЧЕРЕПА (skulls) — то есть ОСНОВЫ для масок; электроника, LED-глаза, вентиляторы",
  proof="В каталоге getfursu.it у мастера отдельными продуктовыми позициями указаны «Blanks» и «Skulls» — то есть производство заготовок, а не только готовых изделий; крафтит с октября 2008",
  act="Не подтверждена", last="Не подтверждена — карточка getfursu.it без даты последнего обновления",
  how="VK", main="https://vk.com/dolls_kingdom_ag", vk="https://vk.com/dolls_kingdom_ag", tg="",
  ig="https://www.instagram.com/hikarinaka_kaze/", site="", email="",
  extra="DeviantArt: https://www.deviantart.com/hikarinaka; Twitter: https://twitter.com/Hikarinaka; YouTube: https://www.youtube.com/user/WindLighter",
  src="https://getfursu.it/c/M000190", src2="https://vk.com/dolls_kingdom_ag",
  why="Производитель именно ОСНОВ (болванок и черепов) — то есть уже работает в той нише, которую мы можем закрыть печатью. Анимегао-маски требуют гладкой точной геометрии, где печать с постобработкой выигрывает у ручной лепки. 17 лет стажа.",
  parts="Болванки и черепа-основы масок, детали глаз, корпуса LED и вентиляции, крепления, мастер-модели",
  rel=5, q="B",
  note="Профиль кигуруми/анимегао, а не классический фурсьют, но по нашему предложению это наиболее точное попадание. Понижен до B: дата последней активности не определяется."),

L(cat="Fursuit parts maker", name="Leimrei Halfneko", nick="leimrei",
  city="не указан", reg="не указан",
  makes="Фурсьюты + 3D-СКУЛЬПТИНГ и 3D-ПЕЧАТЬ голов и BJD-кукол, дизайн персонажей",
  proof="71 пост на Boosty с задокументированным процессом работы, собственное портфолио, открыт приём коммишенов; сам себя называет «Fursuit maker from Russia»",
  act="Умеренная", last="2024-10 — последние посты на Boosty",
  how="Boosty", main="https://boosty.to/leimrei", vk="https://vk.com/public183996998", tg="",
  ig="https://www.instagram.com/leimrei/", site="https://leimrei.carrd.co/", email="",
  extra="", src="https://boosty.to/leimrei", src2="https://leimrei.carrd.co/",
  why="3D-скульптинг и печать заявлены как ОСНОВНАЯ компетенция — этот мастер уже мыслит цифровой моделью, а не только поролоном. С такими проще всего договариваться: им не нужно объяснять технологию, достаточно предложить мощность и качество печати.",
  parts="Печать голов и основ по готовым моделям, мастер-модели, BJD-шарниры, мелкосерийные повторяемые детали",
  rel=5, q="B",
  note="Российское происхождение заявлено самим автором. Понижен до B: последняя активность — октябрь 2024, почти два года назад. Город не указан."),

L(cat="Fursuit parts maker", name="Silent Whales (Фурсьют Мастерская)", nick="club205237013",
  city="не указан", reg="Иркутская область",
  makes="Мини-партиалы (от 25 000 ₽), головы, лапы и компоненты; отдельно предлагают ПЛАСТИКОВЫЕ КОМПЛЕКТУЮЩИЕ для фурсьютов",
  proof="Опубликованный прайс-лист, телефон, собственная VK-группа с портфолио; пластиковые комплектующие заявлены отдельной товарной позицией",
  act="Приостановлена", last="2025-12 — новость о том, что мастерская рассматривает закрытие (мастер занята подготовкой к ЕГЭ), работа приостановлена",
  how="Сайт-визитка VK", main="https://club205237013.orgs.biz/", vk="https://vk.com/club205237013",
  tg="", ig="", site="https://club205237013.orgs.biz/", email="",
  extra="", src="https://club205237013.orgs.biz/", src2="https://vk.com/club205237013",
  why="Уже производят и продают пластиковые комплектующие для фурсьютов — то есть спрос на нашу услугу подтверждён деньгами. При возобновлении работы это готовый канал сбыта деталей, при закрытии — освобождающаяся ниша в Восточной Сибири.",
  parts="Пластиковые комплектующие голов, основы, зубы, когти, детали глаз, крепления",
  rel=5, q="B",
  note="Идеальный профиль по 3D-печати, но реальный риск закрытия: в декабре 2025 объявлено о приостановке. Дешёвый сегмент, молодые мастера. Контакт имеет смысл, только если мастерская возобновила работу."),

L(cat="Fursuit studio", name="FurryJoyStudio", nick="FURRYJS / furryjoystudio",
  city="Москва", reg="Москва",
  makes="Головы и мини-партиалы (боди в планах); АНИМОТРОНИКА, сменные языки, волосы, подвижные брови и уши",
  proof="Собственный сайт-визитка с прайсом, заявлены премейды и коммишены, собственная схема оплаты 30/70, приём оплат через Boosty; работает с марта 2014",
  act="Не подтверждена", last="2023-03-15 — последнее обновление карточки самим мейкером",
  how="Instagram", main="https://www.instagram.com/furryjoystudio/", vk="", tg="",
  ig="https://www.instagram.com/furryjoystudio/", site="https://furryjoystudio.carrd.co/", email="",
  extra="YouTube: https://www.youtube.com/channel/UCUS2e-Dnv6snupCavw8ZY1w",
  src="https://getfursu.it/c/FURRYJS", src2="https://furryjoystudio.carrd.co/",
  why="Анимотроника, подвижные брови и уши, сменные языки — механика, которую невозможно сделать без точных жёстких деталей. Специализация на головах (а не на костюмах целиком) означает высокую долю именно наших компонентов в каждом изделии.",
  parts="Механизмы и шарниры подвижных ушей/бровей/челюстей, корпуса аниматроники, крепления сменных элементов, детали глаз",
  rel=4, q="B",
  note="Оплата через Boosty подтверждает работу в РФ. Понижен до B: карточка не обновлялась с 2023, прямых мессенджеров нет."),

L(cat="Fursuit studio", name="Angel Tigress Fursuit Studio", nick="ANGELTI / angel__tigress",
  city="Москва", reg="Москва",
  makes="Полные плантиград/дигитигрейд-сьюты, головы, партиалы; LED-глаза, вентиляторы, подвижные челюсти",
  proof="Собственный домен с прайсом и публичной страницей очереди заказов (order-queue), магазин на The Dealers Den, профиль на Scritch",
  act="Не подтверждена", last="2021-03-01 — последнее самообновление карточки",
  how="Сайт", main="https://www.angeltigress.com/", vk="", tg="",
  ig="https://www.instagram.com/angel__tigress/", site="https://www.angeltigress.com/", email="",
  extra="Очередь заказов: https://www.angeltigress.com/order-queue/; FA: https://www.furaffinity.net/user/angeltigress/; Twitter: https://twitter.com/Tigress_Zews; Scritch: https://scritch.es/makers/angel-tigress",
  src="https://getfursu.it/c/ANGELTI", src2="https://www.angeltigress.com/price/",
  why="Подвижные челюсти, LED-глаза и вентиляторы в стандартной комплектации — устойчивая потребность в жёстких и механических узлах. Собственный домен с очередью заказов указывает на системную, а не случайную работу.",
  parts="Шарниры подвижных челюстей, корпуса LED-глаз, крепления вентиляторов, основы голов, зубы",
  rel=4, q="B",
  note="Понижен до B: данные не обновлялись с 2021, работоспособность сайта и текущий статус студии требуют проверки."),

L(cat="Private fursuit maker", name="MagicFurry Workshop", nick="magicfurry_workshop / ownerofdreams",
  city="Санкт-Петербург", reg="Санкт-Петербург",
  makes="Фурсьюты (костюмы персонажей)",
  proof="Персональный сайт-визитка мастерской с портфолио и прямым указанием города, профиль мейкера на FurAffinity",
  act="Не подтверждена", last="Актуальная страница-визитка; дата последней работы не подтверждена",
  how="Telegram", main="https://t.me/magicfurry_workshop", vk="", tg="https://t.me/magicfurry_workshop",
  ig="https://instagram.com/magicfurry_workshop", site="https://magicfurryworkshop.carrd.co/", email="",
  extra="Twitter: @magicfurryW; FurAffinity: ownerofdreams",
  src="https://magicfurryworkshop.carrd.co/", src2="",
  why="Профильный питерский мейкер полного цикла с прямым Telegram. Санкт-Петербург — второй по приоритету регион и удобная логистика для отправки деталей.",
  parts=PARTS, rel=4, q="B",
  note="Город подтверждён прямо на сайте («Russia, Saint Petersburg»). Статус приёма заказов не указан — понижен до B."),

L(cat="Fursuit parts maker", name="Jetspear", nick="Jetspear",
  city="не указан", reg="не указан",
  makes="ПРОТОГЕНОВЫЕ ШЛЕМЫ и костюмы (крафт)",
  proof="Профиль исполнителя в разделе заказов российской фурри-площадки m-fur.ru с прямо указанной специализацией «крафт: протогеновы шлемы и костюмы»",
  act="Активна", last="2026-09 — активный профиль исполнителя в разделе заказов",
  how="Профиль m-fur.ru", main="https://m-fur.ru/users/user_otsxqw/",
  vk="", tg="", ig="", site="", email="", extra="",
  src="https://m-fur.ru/users/user_otsxqw/", src2="https://m-fur.ru/postorders/",
  why="Протогены — самая 3D-зависимая ниша фурсьютинга: корпус шлема, рамка визора, крепления и механика печатаются практически целиком. Это максимальное совпадение с нашим профилем из всех найденных мастеров.",
  parts="Корпуса и основы шлемов протогенов, рамки визоров, крепления, шарниры, механические элементы, мелкосерийные повторяемые детали",
  rel=5, q="B",
  note="Ниша совпадает с нашим предложением идеально. Минус: внешних соцсетей в профиле нет, город неизвестен — выход только через площадку. На той же площадке висят открытые заказы «ищу мастера, что делает протогеновы шлемы» — подтверждение неудовлетворённого спроса."),

L(cat="Private fursuit maker", name="Droc Crafts", nick="droc_crafts",
  city="не указан", reg="не указан",
  makes="Головы фурсьютов в тууни-стиле, преимущественно кошачьи",
  proof="Реальный заказ с подтверждённым отзывом на FursuitReview: голова гиены, 2025 г., бюджет $1000-2999, срок 7-12 месяцев; собственное VK-сообщество мастерской",
  act="Активна", last="2026-07-06 — отзыв на FursuitReview по заказу 2025 г.",
  how="VK", main="https://vk.com/club226086292", vk="https://vk.com/club226086292", tg="",
  ig="https://www.instagram.com/droc_crafts/", site="", email="",
  extra="", src="https://fursuitreview.com/m/droc-crafts/", src2="https://vk.com/club226086292",
  why="Свежее подтверждённое производство (2025-2026) в среднем ценовом сегменте. Сорванные сроки, о которых пишет клиент, — как раз тот случай, когда покупные готовые детали сокращают цикл: это прямой аргумент в разговоре.",
  parts=PARTS, rel=3, q="B",
  note="ВНИМАНИЕ: единственный отзыв негативный — клиент жалуется на многократно сорванные сроки. Производство при этом реальное и свежее. Для нас это не дисквалификация, а зацепка для оффера."),

L(cat="Private fursuit maker", name="leon | fursuit workshop", nick="fluffy.leon / _fluffy_leon_",
  city="не указан", reg="не указан",
  makes="Фурсьюты на заказ; публикует готовые сьюты и процесс изготовления",
  proof="93 поста на Boosty с документированным процессом изготовления, сбор средств, открытый приём заказов; параллельные каналы в VK, TikTok и Instagram",
  act="Умеренная", last="2025-01 — последние посты (декабрь 2024 — январь 2025)",
  how="Telegram", main="https://t.me/fluffy_leon", vk="https://vk.com/fluffyleon", tg="https://t.me/fluffy_leon",
  ig="https://www.instagram.com/_fluffy_leon_/", site="https://boosty.to/fluffy.leon", email="",
  extra="TikTok: https://www.tiktok.com/@_fluffy_leon_",
  src="https://boosty.to/fluffy.leon", src2="https://vk.com/fluffyleon",
  why="93 поста с процессом — мастер, который реально делает руками и показывает это. Присутствие сразу на пяти площадках и приём оплат через Boosty означает налаженный поток клиентов.",
  parts=PARTS, rel=3, q="B",
  note="Страна прямо не заявлена, но связка VK + Boosty + рублёвые платежи практически однозначно указывает на РФ. Последняя активность — начало 2025."),

L(cat="Private fursuit maker", name="Macona-Project (Tatiana Vivean)", nick="maconaproject / nyankosensey_madarko",
  city="не указан", reg="не указан",
  makes="Фурри-головы с реалистичной проработкой, полные костюмы, крафт, плюшевые игрушки, косплей; пошивом одежды принципиально не занимаются",
  proof="Альбомы VK с портфолио по разделам (головы, костюмы, крафт, игрушки), работа по артам заказчика, страница на Boosty; по ВикиФур — автор маскота косплей-фестиваля Oni-no-yoru",
  act="Низкая", last="2022-05 — последние посты на Boosty",
  how="VK", main="https://vk.com/maconaproject",
  vk="https://vk.com/maconaproject ; https://vk.com/nyankosensey_madarko", tg="",
  ig="https://boosty.to/macona-project", site="", email="",
  extra="", src="https://boosty.to/macona-project", src2=FRU,
  why="Работа на стыке фурсьютов и косплея плюс изготовление маскота для фестиваля на заказ — подтверждённый коммерческий исполнитель. Реалистичная проработка голов требует точных зубов, глаз и челюстей.",
  parts=PARTS+", механические элементы", rel=3, q="B",
  note="Маскот фестиваля Oni-no-yoru — независимое подтверждение коммерческого заказа. Активность падает: последнее зафиксированное — май 2022."),

# ---------- Каталожные записи: производство подтверждено, активность нет ----------
L(cat="Fursuit studio", name="Selena Snowheart / Lunar Forest", nick="selenovna1 / lunarforest",
  city="Москва", reg="Москва",
  makes="Реалистичные и полу-реалистичные фурсьюты",
  proof="Собственный домен lunarforest.ru, корпоративный email на своём домене, VK-сообщество студии; в ВикиФур отмечена как мастер по созданию реалистичных фурсьютов",
  act="Не подтверждена", last="Запись каталога ~2015-2018; свежая активность не найдена",
  how="Email", main="selena@lunarforest.ru", vk="https://vk.com/club40252050", tg="", ig="",
  site="http://lunarforest.ru", email="selena@lunarforest.ru", extra="",
  src=FRU, src2="https://ru.wikifur.com/wiki/Список_создателей_фурсьютов",
  why="Реалистики — технически самый сложный сегмент: подвижные челюсти, анатомически точные зубы, реалистичные глаза. Прямой потребитель точных печатных деталей, если студия работает.",
  parts="Реалистичные детали глаз, зубы и клыки, подвижные челюсти, шарниры, когти, мастер-модели",
  rel=5, q="C",
  note="Собственный домен и почта на домене — признак серьёзной мастерской на момент записи. VK club40252050 подтверждён двумя независимыми источниками. Email опубликован ею самой как контакт для заказов. Активность требует проверки: оба источника исторические."),

L(cat="Private fursuit maker", name="Crazy Unicorn (Таффка)", nick="Taffka / crazygreenunicorn",
  city="Москва", reg="Москва", makes="Фурсьюты, полу-реалистика; известна фурсьютом Acida («Глюк»)",
  proof="Собственная фурсьют-студия по данным ВикиФур, портфолио на FurAffinity, первое место конкурса фурсьютов Русфуренции 2010",
  act="Не подтверждена", last="Карточка getfursu.it пустая («Last update: never»); подтверждённые работы 2010-2012",
  how="VK", main="https://vk.com/crazygreenunicorn",
  vk="https://vk.com/crazygreenunicorn ; https://vk.com/taffka", tg="",
  ig="https://www.furaffinity.net/user/taffka/", site="", email="",
  extra="", src="https://getfursu.it/c/M000019", src2=FRU,
  why="Профильная московская студия полу-реалистики; при сохранении деятельности — потребность в жёстких деталях головы.",
  parts=PARTS, rel=2, q="C",
  note="Профиль в getfursu.it заведён, но никогда не заполнялся самим мастером — слабый сигнал. Все подтверждения относятся к 2010-2012 гг."),

L(cat="Private fursuit maker", name="Ragnarek Caytam", nick="RagnareK / rcsspvt / ragnarekcaytam",
  city="Москва", reg="Москва", makes="Фурсьюты; также художница",
  proof="Две VK-страницы (личная и мастерской), портфолио на FurAffinity и DeviantArt, канал на YouTube; участница конкурса фурсьютов Русфуренции 2010",
  act="Не подтверждена", last="Запись каталога ~2015-2018; подтверждённая активность 2010-х",
  how="VK", main="https://vk.com/rcsspvt",
  vk="https://vk.com/rcsspvt ; https://vk.com/ragnarekcaytam", tg="", ig="", site="", email="",
  extra="FA: http://www.furaffinity.net/user/RagnareK; DeviantArt: http://ragnarek.deviantart.com/; YouTube: RagnarekC",
  src=FRU, src2="https://ru.wikifur.com/wiki/RagnareK_Caytam",
  why="Московский мейкер с большим портфолио на нескольких площадках; удобная логистика при возобновлении работы.",
  parts=PARTS, rel=2, q="C", note="Подтверждён двумя источниками, но оба описывают активность 2010-х. Контакт в каталоге — Skype, что само по себе говорит о возрасте записи."),

L(cat="Private fursuit maker", name="CatCraft", nick="catcraft / playza",
  city="Казань", reg="Республика Татарстан", makes="Фурсьюты",
  proof="Отдельная VK-группа мастерской (не личная страница) плюс личный аккаунт с портфолио на FurAffinity",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/catcraft", vk="https://vk.com/catcraft", tg="",
  ig="http://www.furaffinity.net/user/playza/", site="", email="",
  extra="", src=FRU, src2="https://vk.com/catcraft",
  why="Единственный подтверждённый мейкер в Казани — ценен для покрытия крупного города-миллионника, где конкуренция за поставщика деталей минимальна.",
  parts=PARTS, rel=3, q="C", note="Город указан в каталоге напрямую. Активность требует проверки."),

L(cat="Private fursuit maker", name="WereWOLFovna / Wolf Factory", nick="werewolfovna / wolf_factory",
  city="не указан", reg="не указан", makes="Фурсьюты, волчья тематика",
  proof="VK-группа под брендом мастерской «wolf_factory», портфолио на FurAffinity и в Instagram",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/wolf_factory", vk="https://vk.com/wolf_factory", tg="",
  ig="https://www.instagram.com/werewolfovna/", site="", email="",
  extra="FA: http://www.furaffinity.net/user/werewolfovna/", src=FRU, src2="https://vk.com/wolf_factory",
  why="Волчьи морды требуют зубов, клыков, носов и деталей глаз — стабильная номенклатура печатных компонентов.",
  parts="Зубы, клыки, носы, детали глаз, когти, основы голов, крепления", rel=3, q="C",
  note="Три площадки под единым брендом — признак настоящего мейкера, а не разового хобби. Активность не подтверждена."),

L(cat="Private fursuit maker", name="Shkaff28 Workshop", nick="shkaff28 / shkaff29",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="Отдельная VK-группа «shkaff28_workshop» помимо личной страницы, портфолио на FurAffinity",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/shkaff28_workshop",
  vk="https://vk.com/shkaff28_workshop ; https://vk.com/id179302092", tg="", ig="", site="", email="",
  extra="FA: http://www.furaffinity.net/user/shkaff29/", src=FRU, src2="https://vk.com/shkaff28_workshop",
  why="Отдельное сообщество-«workshop» указывает на поставленное производство, а не на единичные работы.",
  parts=PARTS, rel=2, q="C", note="ДЕДУП: личная страница id179302092 и сообщество shkaff28_workshop — один лид."),

L(cat="Private fursuit maker", name="Suzamuri Craft", nick="suzamuri / suzamuricraft",
  city="не указан", reg="не указан", makes="Фурсьюты и крафт",
  proof="Отдельная VK-группа под крафт («suzamuricraft») помимо личной страницы",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/suzamuricraft",
  vk="https://vk.com/suzamuricraft ; https://vk.com/suzamuri", tg="", ig="", site="", email="",
  extra="", src=FRU, src2="https://vk.com/suzamuricraft",
  why="Разделение личной страницы и крафт-сообщества — признак систематического потока заказов.",
  parts=PARTS, rel=3, q="C", note="ДЕДУП: suzamuri + suzamuricraft — один лид."),

L(cat="Private fursuit maker", name="Shiro Diablo (Diablo Crafts)", nick="shiro_diablo / diablo_crafts",
  city="не указан", reg="не указан", makes="Фурсьюты и крафт",
  proof="Отдельная VK-группа под брендом мастерской «diablo_crafts», профильный Instagram",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/diablo_crafts", vk="https://vk.com/diablo_crafts", tg="",
  ig="https://www.instagram.com/shiro_diablo/", site="", email="",
  extra="", src=FRU, src2="https://vk.com/diablo_crafts",
  why="Бренд «...Crafts» подразумевает работу не только с тканью, но и с жёсткими материалами — вероятный потребитель печатных деталей.",
  parts=PARTS, rel=3, q="C", note="Город и активность не подтверждены."),

L(cat="Private fursuit maker", name="Chace Bunny", nick="5230chace",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="VK-группа мастерской (club133320983) и портфолио на FurAffinity",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/club133320983", vk="https://vk.com/club133320983", tg="",
  ig="http://www.furaffinity.net/user/5230chace/", site="", email="",
  extra="", src=FRU, src2="https://vk.com/club133320983",
  why="Профильный мейкер с сообществом и портфолио на двух площадках.",
  parts=PARTS, rel=2, q="C", note="Две площадки, но город и активность неизвестны."),

L(cat="Private fursuit maker", name="Milku Minami (Fairy World)", nick="fairy_world_milku",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="Тематическая VK-группа мастерской", act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/fairy_world_milku", vk="https://vk.com/fairy_world_milku",
  tg="", ig="", site="", email="", extra="", src=FRU, src2="https://vk.com/fairy_world_milku",
  why="Профильный мейкер из каталога с оформленным сообществом.", parts=PARTS, rel=2, q="C",
  note="Один источник, одна площадка."),

L(cat="Private fursuit maker", name="Alira Grimm", nick="aliragrimm",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="Включена в каталог мастеров, принимающих заказы; опубликован email для заказов",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/aliragrimm", vk="https://vk.com/aliragrimm", tg="", ig="",
  site="", email="ya-koshara@yandex.ru", extra="", src=FRU, src2="https://vk.com/aliragrimm",
  why="Профильный мейкер из каталога; наличие опубликованного email упрощает первый контакт.",
  parts=PARTS, rel=2, q="C",
  note="Email опубликован ею самой в каталоге как контакт для заказов."),

L(cat="Private fursuit maker", name="Knyaz_wolf456", nick="knyaz.wolf",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="Включён в каталог мастеров; опубликованы два email как контакты для заказов",
  act="Не подтверждена", last="Запись каталога ~2015-2018",
  how="VK", main="https://vk.com/id206006420", vk="https://vk.com/id206006420", tg="",
  ig="https://www.facebook.com/knyaz.wolf", site="", email="MstislavKnyazWolf456@gmail.com",
  extra="Второй email: alexandrabastet2000@gmail.com", src=FRU, src2="https://vk.com/id206006420",
  why="Профильный мейкер из каталога с опубликованными контактами для заказов.",
  parts=PARTS, rel=2, q="C",
  note="Оба email опубликованы в каталоге самим мастером как контакты для заказов. Основной канал в записи — Skype, что указывает на возраст данных."),

L(cat="Private fursuit maker", name="Lossenauro", nick="lossenauro",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="Включён(а) в каталог мастеров, принимающих заказы", act="Не подтверждена",
  last="Запись каталога ~2015-2018", how="VK", main="https://vk.com/lossenauro",
  vk="https://vk.com/lossenauro", tg="", ig="", site="", email="", extra="",
  src=FRU, src2="https://vk.com/lossenauro",
  why="Профильный мейкер из каталога.", parts=PARTS, rel=2, q="C", note="Один источник, одна ссылка."),

L(cat="Private fursuit maker", name="Nyx Cold-Peak", nick="nyx_the_ancient",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="Включён(а) в каталог мастеров, принимающих заказы", act="Не подтверждена",
  last="Запись каталога ~2015-2018", how="VK", main="https://vk.com/nyx_the_ancient",
  vk="https://vk.com/nyx_the_ancient", tg="", ig="", site="", email="", extra="",
  src=FRU, src2="https://vk.com/nyx_the_ancient",
  why="Профильный мейкер из каталога.", parts=PARTS, rel=2, q="C", note="Один источник, одна ссылка."),

L(cat="Private fursuit maker", name="Elofeya", nick="yolkenandhouston",
  city="не указан", reg="не указан", makes="Фурсьюты",
  proof="Включена в каталог мастеров, принимающих заказы", act="Не подтверждена",
  last="Запись каталога ~2015-2018", how="VK", main="https://vk.com/yolkenandhouston",
  vk="https://vk.com/yolkenandhouston", tg="", ig="", site="", email="", extra="",
  src=FRU, src2="https://vk.com/yolkenandhouston",
  why="Профильный мейкер из каталога.", parts=PARTS, rel=2, q="C", note="Один источник, одна ссылка."),

L(cat="Private fursuit maker", name="Фурсьют Мастерская «Пушистик»", nick="club200040868",
  city="Мурманск", reg="Мурманская область",
  makes="Пошив и РЕМОНТ фурсьютов и меховых изделий",
  proof="Публичный телефон, указанный владельцем как контакт для заказов, страница-визитка VK-группы, позиционирование как «профессиональный мастер»",
  act="Не подтверждена", last="Страница-визитка активна на 2026-09; даты работ не подтверждены",
  how="Сайт-визитка VK", main="https://club200040868.orgs.biz/", vk="https://vk.com/club200040868",
  tg="", ig="", site="https://club200040868.orgs.biz/", email="",
  extra="Телефон (опубликован владельцем как контакт для заказов): +7 (911) 804-00-69",
  src="https://club200040868.orgs.biz/", src2="https://vk.com/club200040868",
  why="Занимается в том числе РЕМОНТОМ фурсьютов — а это регулярная потребность в замене сломанных жёстких деталей: зубов, когтей, креплений. Ремонтник закупает детали чаще, чем мейкер. Плюс закрывает Крайний Север, где выбора поставщиков нет.",
  parts="Сменные зубы, когти, крепления, детали глаз, ремкомплекты",
  rel=3, q="C",
  note="Профиль скорее швейно-ремонтный, чем крафтовый, но именно ремонт даёт повторяющийся спрос на детали. Активность не подтверждена."),
]
