# -*- coding: utf-8 -*-
"""Сид-набор лидов, собранных основным исследователем (не агентами)."""
import json
D = "2026-09-15"
def L(**k):
    r = {"Дата проверки": D}
    m = {"cat":"Категория","name":"Название мастерской / имя мастера","nick":"Никнейм","city":"Город",
         "reg":"Регион","makes":"Что производит","proof":"Признаки собственного производства",
         "act":"Активность","last":"Последняя обнаруженная активность","how":"Основной способ связи",
         "main":"Основной контакт","vk":"VK","tg":"Telegram","ig":"Instagram / другая соцсеть",
         "site":"Сайт","email":"Email","extra":"Дополнительные контакты","src":"Основной источник",
         "src2":"Дополнительный источник","why":"Почему подходит нашей мастерской",
         "parts":"Потенциально интересующие детали / услуги","rel":"Коммерческая релевантность 1-5",
         "q":"Качество лида A/B/C","note":"Комментарий исследователя"}
    for a,b in m.items(): r[b] = k.get(a,"")
    return r

FURSUIT_PARTS = "Основы голов, глаза, зубы, клыки, когти, крепления, шарниры, декоративные детали"
FR = "https://fursuitreview.com/shiporigin/russia/"
FRU = "https://fursuit.ru/i-want-fursuit/fursuit-makers-list"
WF = "https://ru.wikifur.com/wiki/Список_создателей_фурсьютов"

fursuit = [
 L(cat="Fursuit studio", name="CofferretCraft (TakahiroReta)", nick="cofferret_craft / TakahiroReta",
   city="Москва / Ярославль", reg="Москва",
   makes="Фурсьюты в стиле кемоно и мультяшном, 3D-печатные основы, тематический мерч",
   proof="Собственный сайт-мастерская с портфолио по годам, очередь заказов, опубликованные отзывы, две офлайн-точки ('Ушастая полка' Москва, 'Шиба полки' Ярославль), описан техпроцесс: мех Big Z/Howl, печать в PETG/PLA/TPU",
   act="Активна", last="2026 (актуальный сайт, действующая очередь заказов)",
   how="Telegram", main="https://t.me/cofferretcraft",
   vk="https://vk.com/cofferretcraft", tg="https://t.me/cofferretcraft",
   ig="https://instagram.com/cofferret_craft", site="https://cofferret.store/",
   email="takahiroreta@gmail.com",
   extra="VK личный: https://vk.com/kot_uzumaki; FA: takahiroreta; Twitter: @CFerretCraft; DealersDen: takahiroreta",
   src="https://cofferret.store/", src2=FR,
   why="Действующая студия с постоянным потоком заказов, УЖЕ использует 3D-печать (PETG/PLA/TPU) в своих фурсьютах — то есть спрос на печатные детали подтверждён. Кандидат на аутсорс печати при росте очереди и на сложные детали, которые тяжело печатать на своём парке.",
   parts=FURSUIT_PARTS + ", мелкосерийные повторяемые детали, мастер-модели",
   rel=5, q="A",
   note="Сильнейший лид базы. Печатает сама — значит, это не 'холодный' рынок, а осознанный потребитель услуги. Продавать как расширение мощности/качества, а не как новую идею. Связка ников подтверждена: kot_uzumaki = cofferretcraft = takahiroreta."),

 L(cat="Fursuit studio", name="ФурриСтудио / Furry Studio", nick="ElliFox / furrystudio / rusfurry",
   city="Москва", reg="Москва",
   makes="Полные фурсьюты, головы, лапы, хвосты; кигуруми, антро-плюш, бейджи",
   proof="Собственный сайт с галереей работ и формой заказа, описание техпроцесса, канал на YouTube, студия работает с 2013 г. (основана под Русфуренцию 2014)",
   act="Активна", last="2026 (действующий сайт с приёмом заказов)",
   how="Telegram", main="https://t.me/ElliFox",
   vk="https://vk.com/rusfurry", tg="https://t.me/ElliFox",
   ig="https://instagram.com/furrystudio", site="https://thefurrystudio.com/",
   email="", extra="Twitter: twitter.com/furrystudio; FA: furrystudio; YouTube: FurryStudio; Boosty: https://boosty.to/furrystudio",
   src="https://www.thefurrystudio.com/sdelat-zakaz", src2=WF,
   why="Одна из старейших и крупнейших студий РФ, делает полу-реалистику — самый требовательный к жёстким деталям стиль (челюсти, зубы, глазницы, крепления). Объём заказов оправдывает мелкосерийное производство повторяемых деталей.",
   parts="Основы голов, глаза, зубы/клыки, когти, крепления, шарниры челюсти, декоративные детали",
   rel=5, q="A",
   note="Историческая студия Баст/Габриэль/Честера, подтверждена и ВикиФур, и собственным сайтом. Email на сайте скрыт от спама — не выписывал, чтобы не выдумывать."),

 L(cat="Private fursuit maker", name="MagicFurry Workshop", nick="magicfurry_workshop / ownerofdreams",
   city="Санкт-Петербург", reg="Санкт-Петербург",
   makes="Фурсьюты (костюмы персонажей)",
   proof="Персональный сайт-визитка мастерской с портфолио и указанием города, профили мейкера на FurAffinity",
   act="Активна (умеренно)", last="Актуальная страница-визитка; точная дата последней работы не подтверждена",
   how="Telegram", main="https://t.me/magicfurry_workshop",
   vk="", tg="https://t.me/magicfurry_workshop",
   ig="https://instagram.com/magicfurry_workshop", site="https://magicfurryworkshop.carrd.co/",
   email="", extra="Twitter: @magicfurryW; FurAffinity: ownerofdreams",
   src="https://magicfurryworkshop.carrd.co/", src2="",
   why="Профильный питерский мейкер полного цикла — регулярная потребность в основах голов, глазах, зубах и креплениях.",
   parts=FURSUIT_PARTS, rel=4, q="B",
   note="Город подтверждён прямо на сайте ('Russia, Saint Petersburg'). Статус commissions на странице не указан — понизил до B."),

 L(cat="Fursuit parts maker", name="Jetspear", nick="Jetspear",
   city="не указан", reg="не указан",
   makes="Протогеновые шлемы и костюмы (крафт)",
   proof="Профиль исполнителя в разделе заказов российской фурри-площадки m-fur.ru с указанием специализации 'крафт: протогены'",
   act="Активна", last="2026 (активный профиль исполнителя в разделе заказов)",
   how="Профиль m-fur.ru", main="https://m-fur.ru/users/user_otsxqw/",
   vk="", tg="", ig="", site="", email="",
   extra="", src="https://m-fur.ru/users/user_otsxqw/", src2="https://m-fur.ru/postorders/",
   why="Протогены — самая 3D-зависимая ниша фурсьютинга: корпус шлема, визор-рамка, крепления, механика полностью печатаются. Максимальная релевантность нашему профилю.",
   parts="Корпуса/основы шлемов протогенов, рамки визоров, крепления, шарниры, механические элементы, мелкосерийные повторяемые детали",
   rel=5, q="B",
   note="Ниша идеально совпадает с нашим предложением. Минус: внешних соцсетей в профиле не найдено, город неизвестен — нужен контакт через площадку."),

 L(cat="Fursuit studio", name="Crazy Unicorn (Таффка)", nick="Таффка / taffka / crazygreenunicorn",
   city="Москва", reg="Москва",
   makes="Фурсьюты (полу-реалистика), известна фурсьютом Acida/Глюк",
   proof="Собственная фурсьют-студия (ВикиФур), портфолио работ на FurAffinity, 1-е место конкурса фурсьютов Русфуренции 2010",
   act="Не подтверждена", last="Подтверждённые работы 2010-2012; свежая активность не подтверждена",
   how="VK", main="https://vk.com/crazygreenunicorn",
   vk="https://vk.com/crazygreenunicorn ; https://vk.com/taffka", tg="", ig="",
   site="", email="", extra="FurAffinity: http://furaffinity.net/user/taffka",
   src=FRU, src2=WF,
   why="Профильная московская студия полу-реалистики; при сохранении деятельности — потребность в жёстких деталях головы.",
   parts=FURSUIT_PARTS, rel=3, q="C",
   note="Понижено до C: оба источника-каталога — исторические (2010-е). Требуется проверка, работает ли студия сейчас; VK напрямую не читается."),

 L(cat="Private fursuit maker", name="Samira / Crafts Fur Raptors", nick="Samira / lygaryk / crafts_fur_raptors",
   city="Красноярск", reg="Красноярский край",
   makes="Фурсьюты, специализация на рапторах/драконах (сложные морды с зубами и когтями)",
   proof="Профиль мейкера в базе FursuitReview (shipping origin Russia), портфолио в Instagram, платная подписка Boosty, аккаунт FurAffinity",
   act="Активна", last="Актуальный профиль FursuitReview и Boosty",
   how="Instagram", main="https://instagram.com/crafts_fur_raptors",
   vk="https://vk.com/suit_of_samira", tg="", ig="https://instagram.com/crafts_fur_raptors",
   site="https://boosty.to/craftsfurraptors", email="Lygaryk@gmail.com",
   extra="Twitter: https://twitter.com/lygaryk; FurAffinity: samiraredhusky1; FursuitReview: https://fursuitreview.com/m/crafts-fur-raptors/",
   src="https://fursuitreview.com/m/crafts-fur-raptors/", src2=FRU,
   why="Рапторы и драконы = максимум жёстких деталей: зубы, клыки, когти, подвижные челюсти, детали глаз. Именно тот профиль, где 3D-печать даёт мастеру наибольший выигрыш.",
   parts="Зубы, клыки, когти, детали глаз, подвижные челюсти/шарниры, крепления, мастер-модели",
   rel=5, q="A",
   note="ВАЖНАЯ ДЕДУПЛИКАЦИЯ: Twitter 'lygaryk' в профиле Crafts Fur Raptors совпадает с email Lygaryk@gmail.com мастера Samira (Красноярск) из каталога fursuit.ru. Объединено в один лид."),

 L(cat="Fursuit studio", name="Haze Valley (Essorille)", nick="essorille / hazevalley",
   city="не указан", reg="не указан",
   makes="Фурсьюты и крафт-изделия",
   proof="Собственный сайт студии, магазин на Etsy (essorillecraft), профиль в базе FursuitReview с origin Russia, портфолио на DeviantArt",
   act="Активна", last="Актуальные сайт и профиль FursuitReview",
   how="Сайт", main="https://eng.hazevalley.ru/",
   vk="", tg="", ig="https://instagram.com/essorille", site="https://eng.hazevalley.ru/",
   email="", extra="DeviantArt: essorille; Etsy: https://www.etsy.com/shop/essorillecraft; Tumblr: essorille.tumblr.com; FursuitReview: https://fursuitreview.com/m/haze-valley/",
   src="https://fursuitreview.com/m/haze-valley/", src2="https://eng.hazevalley.ru/",
   why="Студия с собственным доменом в зоне .ru и коммерческой витриной — признак поставленного на поток производства и готовности к закупкам комплектующих.",
   parts=FURSUIT_PARTS + ", формы и мастер-модели", rel=4, q="B",
   note="Российское происхождение подтверждено доменом .ru и фильтром FursuitReview. Город не указан ни в одном источнике."),

 L(cat="Private fursuit maker", name="Droc Crafts", nick="droc_crafts",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Профиль мейкера в базе FursuitReview (origin Russia), собственное VK-сообщество мастерской, портфолио в Instagram",
   act="Активна", last="VK-сообщество создано недавно (club226086292 — свежий диапазон ID)",
   how="VK", main="https://vk.com/club226086292", vk="https://vk.com/club226086292",
   tg="", ig="https://instagram.com/droc_crafts", site="", email="",
   extra="FursuitReview: https://fursuitreview.com/m/droc-crafts/",
   src="https://fursuitreview.com/m/droc-crafts/", src2="https://vk.com/club226086292",
   why="Молодая активная мастерская — наиболее восприимчивы к предложениям аутсорса деталей, так как ещё не выстроили своё производство.",
   parts=FURSUIT_PARTS, rel=4, q="B",
   note="Высокий ID VK-сообщества косвенно указывает на недавнее создание (2024+). Содержимое VK проверить напрямую не удалось."),

 L(cat="Private fursuit maker", name="FurryYana", nick="furry_yana",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Профиль мейкера в базе FursuitReview (origin Russia), собственный Telegram-канал и Instagram-портфолио",
   act="Активна", last="Актуальный профиль FursuitReview",
   how="Telegram", main="https://t.me/furryyana", vk="", tg="https://t.me/furryyana",
   ig="https://instagram.com/furry_yana", site="", email="",
   extra="FursuitReview: https://fursuitreview.com/m/furryyana/",
   src="https://fursuitreview.com/m/furryyana/", src2="",
   why="Действующий мейкер полного цикла с прямым каналом связи в Telegram.",
   parts=FURSUIT_PARTS, rel=4, q="B", note="Город не указан ни в одном источнике."),

 L(cat="Private fursuit maker", name="WesternVibe Saloon", nick="wv_saloon / kavaynu",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Профиль в базе FursuitReview (origin Russia), собственная галерея мейкера на Furtrack (фото готовых работ), FurAffinity",
   act="Активна", last="Галерея мейкера на Furtrack (фотоподтверждение сданных костюмов)",
   how="Instagram", main="https://www.instagram.com/western_vibe_saloon/",
   vk="", tg="", ig="https://www.instagram.com/western_vibe_saloon/", site="", email="",
   extra="FurAffinity: https://www.furaffinity.net/user/kavaynu/; Furtrack: https://www.furtrack.com/index/maker:wv_saloon; FursuitReview: https://fursuitreview.com/m/westernvibe-saloon/",
   src="https://fursuitreview.com/m/westernvibe-saloon/", src2="https://www.furtrack.com/index/maker:wv_saloon",
   why="Наличие отдельной maker-галереи на Furtrack — сильный признак регулярного выпуска костюмов, а не единичных работ.",
   parts=FURSUIT_PARTS, rel=4, q="B", note="Галерея Furtrack — независимое подтверждение реального производства."),

 L(cat="Private fursuit maker", name="Smoke Dragon Studio", nick="smokedragonstudiop",
   city="не указан", reg="не указан", makes="Фурсьюты, драконья тематика",
   proof="Профиль мейкера в базе FursuitReview (origin Russia), портфолио в Instagram",
   act="Не подтверждена", last="Актуальный профиль FursuitReview; даты работ не подтверждены",
   how="Instagram", main="https://instagram.com/smokedragonstudiop",
   vk="", tg="", ig="https://instagram.com/smokedragonstudiop", site="", email="",
   extra="FursuitReview: https://fursuitreview.com/m/smoke-dragon-studio/",
   src="https://fursuitreview.com/m/smoke-dragon-studio/", src2="",
   why="Драконья тематика = рога, шипы, зубы, когти, гребни — почти целиком печатные детали.",
   parts="Рога, шипы, гребни, зубы, клыки, когти, детали глаз, крепления", rel=4, q="C",
   note="Единственный канал связи — Instagram, недоступный для прямой проверки. Активность не подтверждена."),

 L(cat="Private fursuit maker", name="Sunraise", nick="_sun_raise_",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Профиль мейкера в базе FursuitReview (origin Russia), портфолио в Instagram",
   act="Не подтверждена", last="Актуальный профиль FursuitReview",
   how="Instagram", main="https://instagram.com/_sun_raise_",
   vk="", tg="", ig="https://instagram.com/_sun_raise_", site="", email="",
   extra="FursuitReview: https://fursuitreview.com/m/sunraise/",
   src="https://fursuitreview.com/m/sunraise/", src2="",
   why="Профильный мейкер — потенциальная потребность в основах, глазах и зубах.",
   parts=FURSUIT_PARTS, rel=3, q="C", note="Минимум публичных данных: только Instagram. Город неизвестен."),

 L(cat="Private fursuit maker", name="Pinkfluff", nick="pinqfluff",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Профиль мейкера в базе FursuitReview (origin Russia), портфолио в Instagram",
   act="Не подтверждена", last="Актуальный профиль FursuitReview",
   how="Instagram", main="https://instagram.com/pinqfluff",
   vk="", tg="", ig="https://instagram.com/pinqfluff", site="", email="",
   extra="FursuitReview: https://fursuitreview.com/m/pinkfluff/",
   src="https://fursuitreview.com/m/pinkfluff/", src2="",
   why="Профильный мейкер — потенциальная потребность в жёстких комплектующих.",
   parts=FURSUIT_PARTS, rel=3, q="C", note="Минимум публичных данных: только Instagram."),

 L(cat="Private fursuit maker", name="Fur Rain", nick="fur_rain",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Профиль мейкера в базе FursuitReview (origin Russia), портфолио в Instagram",
   act="Не подтверждена", last="Актуальный профиль FursuitReview",
   how="Instagram", main="https://instagram.com/fur_rain",
   vk="", tg="", ig="https://instagram.com/fur_rain", site="", email="",
   extra="FursuitReview: https://fursuitreview.com/m/fur-rain/",
   src="https://fursuitreview.com/m/fur-rain/", src2="",
   why="Профильный мейкер — потенциальная потребность в жёстких комплектующих.",
   parts=FURSUIT_PARTS, rel=3, q="C", note="Минимум публичных данных: только Instagram."),

 L(cat="Fursuit studio", name="Selena Snowheart / Lunar Forest", nick="Selena / lunarforest",
   city="Москва", reg="Москва",
   makes="Реалистичные и полу-реалистичные фурсьюты",
   proof="Собственный сайт-мастерская (lunarforest.ru), VK-сообщество студии, опубликован рабочий email для заказов; отмечена в ВикиФур как мастер по реалистикам",
   act="Не подтверждена", last="Присутствие в каталогах; свежие работы не подтверждены",
   how="Email", main="selena@lunarforest.ru",
   vk="https://vk.com/club40252050", tg="", ig="", site="http://lunarforest.ru",
   email="selena@lunarforest.ru", extra="",
   src=FRU, src2=WF,
   why="Реалистики — технически самый сложный сегмент: подвижные челюсти, анатомичные зубы, реалистичные глаза. Прямой потребитель точных печатных деталей.",
   parts="Реалистичные глаза, зубы и клыки, подвижные челюсти, шарниры, когти, мастер-модели",
   rel=5, q="C",
   note="Email опубликован самим мастером в каталоге как контакт для заказов. VK club40252050 подтверждён двумя независимыми источниками (fursuit.ru и ВикиФур). Активность требует проверки — каталоги исторические."),

 L(cat="Fursuit studio", name="FurR.CluB (Prisheliss)", nick="Prisheliss / furr.club",
   city="не указан", reg="не указан",
   makes="Фурсьюты на заказ (студия работает с 2013 г.)",
   proof="Собственный сайт-студия furr.club с портфолио, VK-сообщество, опубликованный email для заказов",
   act="Заказы закрыты", last="Сайт актуален; в каталоге помечено 'заказы временно не принимаются'",
   how="Сайт", main="https://furr.club/", vk="https://vk.com/furr.club", tg="", ig="",
   site="https://furr.club/", email="spacealienfox@gmail.com", extra="",
   src=FRU, src2="https://furr.club/",
   why="Студия с 12-летней историей; при возобновлении набора — стабильный потребитель повторяемых деталей.",
   parts=FURSUIT_PARTS, rel=3, q="C",
   note="Закрытые commissions прямо указаны в каталоге — понижено до C. Сайт отдаёт 403 при прямой проверке, данные по поисковым сниппетам."),

 L(cat="Private fursuit maker", name="Ugolek Fursuit Studio (UshGalesh)", nick="ugoleksuits / ugolek_fursuitstudio",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Отдельное VK-сообщество мастерской (не личная страница) и профильный Instagram студии",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/ugoleksuits", vk="https://vk.com/ugoleksuits", tg="",
   ig="https://www.instagram.com/ugolek_fursuitstudio/", site="", email="",
   extra="", src=FRU, src2="",
   why="Оформленная как студия мастерская — потребность в основах, глазах, зубах, когтях.",
   parts=FURSUIT_PARTS, rel=3, q="C",
   note="Наличие и VK-сообщества, и Instagram с 'fursuitstudio' в нике — признак системной работы, но активность не проверена."),

 L(cat="Private fursuit maker", name="WereWOLFovna / Wolf Factory", nick="werewolfovna / wolf_factory",
   city="не указан", reg="не указан", makes="Фурсьюты (волчья тематика)",
   proof="VK-сообщество мастерской 'wolf_factory', портфолио на FurAffinity и в Instagram",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/wolf_factory", vk="https://vk.com/wolf_factory", tg="",
   ig="https://www.instagram.com/werewolfovna/", site="", email="",
   extra="FurAffinity: http://www.furaffinity.net/user/werewolfovna/",
   src=FRU, src2="",
   why="Профильный мейкер с оформленной мастерской; волчьи морды требуют зубов, клыков, носов и деталей глаз.",
   parts="Зубы, клыки, носы, детали глаз, когти, основы голов, крепления", rel=3, q="C",
   note="Три площадки под одним брендом — признак настоящего мейкера. Активность не подтверждена (каталог исторический)."),

 L(cat="Private fursuit maker", name="Shkaff28", nick="shkaff28",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Отдельное VK-сообщество-мастерская (shkaff28_workshop) помимо личной страницы, портфолио на FurAffinity",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/shkaff28_workshop",
   vk="https://vk.com/shkaff28_workshop ; https://vk.com/id179302092", tg="", ig="", site="", email="",
   extra="FurAffinity: http://www.furaffinity.net/user/shkaff29/", src=FRU, src2="",
   why="Отдельное сообщество-'workshop' — признак поставленного производства.",
   parts=FURSUIT_PARTS, rel=3, q="C",
   note="ДЕДУП: личная страница id179302092 и сообщество shkaff28_workshop — один лид."),

 L(cat="Private fursuit maker", name="CatCraft", nick="catcraft / playza",
   city="Казань", reg="Республика Татарстан", makes="Фурсьюты",
   proof="VK-сообщество мастерской, портфолио на FurAffinity",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/catcraft", vk="https://vk.com/catcraft", tg="", ig="", site="", email="",
   extra="FurAffinity: http://www.furaffinity.net/user/playza/", src=FRU, src2="",
   why="Единственный подтверждённый каталогом мейкер в Казани — ценен для покрытия региона-миллионника.",
   parts=FURSUIT_PARTS, rel=3, q="C",
   note="Город указан в каталоге. Активность требует проверки."),

 L(cat="Private fursuit maker", name="RagnareK Caytam", nick="RagnareK / rcsspvt",
   city="Москва", reg="Москва", makes="Фурсьюты; художница",
   proof="Два VK-сообщества, портфолио на FurAffinity и DeviantArt, канал YouTube; участница конкурса фурсьютов Русфуренции 2010",
   act="Не подтверждена", last="Подтверждённая активность ~2010-е",
   how="VK", main="https://vk.com/rcsspvt",
   vk="https://vk.com/rcsspvt ; https://vk.com/ragnarekcaytam", tg="", ig="", site="", email="",
   extra="FurAffinity: http://www.furaffinity.net/user/RagnareK; DeviantArt: http://ragnarek.deviantart.com/; YouTube: RagnarekC",
   src=FRU, src2="https://ru.wikifur.com/wiki/RagnareK_Caytam",
   why="Московский мейкер с большим портфолио; при активности — потребность в деталях головы.",
   parts=FURSUIT_PARTS, rel=3, q="C", note="Подтверждена двумя источниками, но оба описывают активность 2010-х."),

 L(cat="Private fursuit maker", name="Shiro Diablo (Diablo Crafts)", nick="shiro_diablo / diablo_crafts",
   city="не указан", reg="не указан", makes="Фурсьюты и крафт",
   proof="VK-сообщество 'diablo_crafts', профильный Instagram",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/diablo_crafts", vk="https://vk.com/diablo_crafts", tg="",
   ig="https://www.instagram.com/shiro_diablo/", site="", email="", extra="", src=FRU, src2="",
   why="Бренд '...Crafts' и профильное сообщество — признак мастерской, а не разового хобби.",
   parts=FURSUIT_PARTS, rel=3, q="C", note="Город и активность не подтверждены."),

 L(cat="Private fursuit maker", name="Krafi / TETRIS workshop", nick="Krafi / kraficat",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Собственная мастерская 'TETRIS workshop', портфолио на FurAffinity и DeviantArt, прямой Telegram",
   act="Не подтверждена", last="Не подтверждена",
   how="Telegram", main="https://t.me/Krafi", vk="https://vk.com/kartiki", tg="https://t.me/Krafi",
   ig="https://www.instagram.com/kraficat", site="", email="",
   extra="FurAffinity: krafi; DeviantArt: kraficat; Twitter: @CatKrafi; Tumblr: kraficat",
   src=FRU, src2="",
   why="Мастер с оформленной мастерской и прямым Telegram — удобный канал для B2B-контакта.",
   parts=FURSUIT_PARTS, rel=3, q="C",
   note="Максимальное число площадок под одним ником (6) — уверенная идентификация одного лица. Активность не подтверждена."),

 L(cat="Private fursuit maker", name="Arvin Pol (Arvin's Lair)", nick="Arvin Pol / arvinslair",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Собственный сайт arvinslair.com и VK-сообщество",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/club68485737", vk="https://vk.com/club68485737", tg="", ig="",
   site="http://arvinslair.com/", email="", extra="", src=FRU, src2="",
   why="Наличие собственного домена — признак серьёзного отношения к мастерской как к бизнесу.",
   parts=FURSUIT_PARTS, rel=3, q="C", note="Работоспособность сайта не проверена."),

 L(cat="Private fursuit maker", name="Suzamuri", nick="suzamuri / suzamuricraft",
   city="не указан", reg="не указан", makes="Фурсьюты и крафт",
   proof="Отдельное VK-сообщество для крафта (suzamuricraft) помимо личной страницы",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/suzamuricraft",
   vk="https://vk.com/suzamuricraft ; https://vk.com/suzamuri", tg="", ig="", site="", email="",
   extra="", src=FRU, src2="",
   why="Разделение личной страницы и крафт-сообщества — признак систематических заказов.",
   parts=FURSUIT_PARTS, rel=3, q="C", note="ДЕДУП: suzamuri + suzamuricraft — один лид."),

 L(cat="Private fursuit maker", name="Tatiana Vivean / Macona Project", nick="Vivean / maconaproject",
   city="не указан", reg="не указан",
   makes="Фурсьюты в стиле полу-реалистика, фурри-косплей; маскот косплей-фестиваля Oni-no-yoru",
   proof="Два VK-сообщества проекта; в ВикиФур отмечена как автор маскота фестиваля Oni-no-yoru — подтверждение заказной работы",
   act="Не подтверждена", last="Не подтверждена",
   how="VK", main="https://vk.com/maconaproject",
   vk="https://vk.com/maconaproject ; https://vk.com/nyankosensey_madarko", tg="", ig="", site="", email="",
   extra="", src=FRU, src2=WF,
   why="Работа на стыке фурсьютов и косплея + изготовление маскота на заказ = подтверждённый коммерческий исполнитель. Полу-реалистика требует точных деталей головы.",
   parts=FURSUIT_PARTS + ", механические элементы", rel=4, q="C",
   note="Маскот фестиваля — независимое подтверждение коммерческого заказа. Активность требует проверки."),

 L(cat="Private fursuit maker", name="Alira Grimm", nick="aliragrimm", city="не указан", reg="не указан",
   makes="Фурсьюты", proof="Профиль в каталоге мастеров fursuit.ru с личной VK-страницей",
   act="Не подтверждена", last="Не подтверждена", how="VK", main="https://vk.com/aliragrimm",
   vk="https://vk.com/aliragrimm", tg="", ig="", site="", email="", extra="", src=FRU, src2="",
   why="Профильный мейкер из каталога.", parts=FURSUIT_PARTS, rel=2, q="C",
   note="Только одна ссылка и один источник. Кандидат на дополнительную проверку."),

 L(cat="Private fursuit maker", name="Lossenauro", nick="lossenauro", city="не указан", reg="не указан",
   makes="Фурсьюты", proof="Профиль в каталоге мастеров fursuit.ru с личной VK-страницей",
   act="Не подтверждена", last="Не подтверждена", how="VK", main="https://vk.com/lossenauro",
   vk="https://vk.com/lossenauro", tg="", ig="", site="", email="", extra="", src=FRU, src2="",
   why="Профильный мейкер из каталога.", parts=FURSUIT_PARTS, rel=2, q="C",
   note="Только одна ссылка и один источник."),

 L(cat="Private fursuit maker", name="Nyx Cold-Peak", nick="nyx_the_ancient", city="не указан", reg="не указан",
   makes="Фурсьюты", proof="Профиль в каталоге мастеров fursuit.ru с личной VK-страницей",
   act="Не подтверждена", last="Не подтверждена", how="VK", main="https://vk.com/nyx_the_ancient",
   vk="https://vk.com/nyx_the_ancient", tg="", ig="", site="", email="", extra="", src=FRU, src2="",
   why="Профильный мейкер из каталога.", parts=FURSUIT_PARTS, rel=2, q="C",
   note="Только одна ссылка и один источник."),

 L(cat="Private fursuit maker", name="Milku Minami", nick="fairy_world_milku", city="не указан", reg="не указан",
   makes="Фурсьюты", proof="VK-сообщество проекта 'fairy_world_milku'",
   act="Не подтверждена", last="Не подтверждена", how="VK", main="https://vk.com/fairy_world_milku",
   vk="https://vk.com/fairy_world_milku", tg="", ig="", site="", email="", extra="", src=FRU, src2="",
   why="Профильный мейкер из каталога.", parts=FURSUIT_PARTS, rel=2, q="C", note="Один источник."),

 L(cat="Private fursuit maker", name="Elofeya", nick="yolkenandhouston", city="не указан", reg="не указан",
   makes="Фурсьюты", proof="Профиль в каталоге мастеров fursuit.ru с VK-страницей",
   act="Не подтверждена", last="Не подтверждена", how="VK", main="https://vk.com/yolkenandhouston",
   vk="https://vk.com/yolkenandhouston", tg="", ig="", site="", email="", extra="", src=FRU, src2="",
   why="Профильный мейкер из каталога.", parts=FURSUIT_PARTS, rel=2, q="C", note="Один источник."),

 L(cat="Private fursuit maker", name="Chace Bunny", nick="5230chace", city="не указан", reg="не указан",
   makes="Фурсьюты", proof="VK-сообщество и портфолио на FurAffinity",
   act="Не подтверждена", last="Не подтверждена", how="VK", main="https://vk.com/club133320983",
   vk="https://vk.com/club133320983", tg="", ig="", site="", email="",
   extra="FurAffinity: http://www.furaffinity.net/user/5230chace/", src=FRU, src2="",
   why="Профильный мейкер с сообществом и портфолио.", parts=FURSUIT_PARTS, rel=2, q="C",
   note="Две площадки, но активность и город неизвестны."),

 L(cat="Private fursuit maker", name="Knyaz_wolf456", nick="Knyaz_wolf456", city="не указан", reg="не указан",
   makes="Фурсьюты", proof="Профиль в каталоге мастеров fursuit.ru с VK-страницей",
   act="Не подтверждена", last="Не подтверждена", how="VK", main="https://vk.com/id206006420",
   vk="https://vk.com/id206006420", tg="", ig="", site="", email="",
   extra="Facebook: https://www.facebook.com/knyaz.wolf", src=FRU, src2="",
   why="Профильный мейкер из каталога.", parts=FURSUIT_PARTS, rel=2, q="C",
   note="Контакты в каталоге устаревшие (Skype как основной канал)."),
]

unverified = [
 L(cat="Fursuit parts maker", name="фурсьют мастерская (Instagram)", nick="_fursuit_workshop_",
   city="не указан", reg="не указан",
   makes="Готовые фурсьюты и изготовление на заказ",
   proof="Instagram-профиль мастерской (~1 947 подписчиков) с указанием продажи готовых сьютов и приёма заказов",
   act="Не подтверждена", last="Не подтверждена",
   how="Instagram", main="https://www.instagram.com/_fursuit_workshop_/",
   vk="", tg="", ig="https://www.instagram.com/_fursuit_workshop_/", site="", email="", extra="",
   src="https://www.instagram.com/_fursuit_workshop_/", src2="",
   why="Заявлен приём заказов на фурсьюты — потенциальная потребность в основах и жёстких деталях.",
   parts=FURSUIT_PARTS, rel=3, q="Требует проверки",
   note="Instagram недоступен для прямой проверки (429/логин). Российская принадлежность НЕ подтверждена — найден по русскоязычному запросу, но это не доказательство. Требует ручной проверки."),

 L(cat="Private fursuit maker", name="Monsters Factory", nick="monsters_factory_64",
   city="не указан (возможно Саратовская обл. — по '64' в нике)", reg="не указан",
   makes="Фурсьюты",
   proof="Автор прямо заявляет в Instagram-ролике: 'I am a fursuit maker from Russia'",
   act="Не подтверждена", last="Не подтверждена",
   how="Instagram", main="https://www.instagram.com/monsters_factory_64/",
   vk="", tg="", ig="https://www.instagram.com/monsters_factory_64/", site="", email="", extra="",
   src="https://www.instagram.com/monsters_factory_64/reel/C4ya-oKNu51/", src2="",
   why="Самоидентификация как fursuit maker из России — профильный лид при подтверждении активности.",
   parts=FURSUIT_PARTS, rel=3, q="Требует проверки",
   note="Российское происхождение заявлено самим автором. Гипотеза о Саратове по цифрам '64' (код региона) — ДОГАДКА, не проверена. Instagram недоступен для прямой проверки."),

 L(cat="Fursuit parts maker", name="Studio3D (маска раптора, Wildberries)", nick="Studio3D",
   city="не указан", reg="не указан",
   makes="3D-печатные маски динозавров/рапторов, основы для фурсьютов",
   proof="Товар на Wildberries: 'маска динозавра раптора Studio3D, основа для фурсьют'",
   act="Не подтверждена", last="Не подтверждена",
   how="Маркетплейс", main="https://www.wildberries.ru/catalog/263400845/detail.aspx",
   vk="", tg="", ig="", site="", email="", extra="",
   src="https://www.wildberries.ru/catalog/263400845/detail.aspx", src2="",
   why="Печатает основы для фурсьютов — это скорее КОНКУРЕНТ, чем клиент, но может быть партнёром по загрузке мощностей или заказчиком нестандартных деталей.",
   parts="Основы голов, мастер-модели", rel=2, q="Требует проверки",
   note="ВНИМАНИЕ: профиль пересекается с нашим — конкурент по 3D-печати основ. Прямых контактов мастера, кроме карточки маркетплейса, не найдено."),

 L(cat="Fursuit studio", name="Studio Fursuit RSB", nick="studiofursuit-rsb",
   city="не указан", reg="не указан", makes="Фурсьюты",
   proof="Упомянута в ВикиФур как студия изготовления фурсьютов, есть собственный домен",
   act="Не подтверждена", last="Не подтверждена",
   how="Сайт", main="http://studiofursuit-rsb.com/", vk="", tg="", ig="",
   site="http://studiofursuit-rsb.com/", email="", extra="",
   src="https://ru.wikifur.com/wiki/Studio_Fursuit_RSB", src2="",
   why="Оформленная студия — потенциальный потребитель повторяемых деталей.",
   parts=FURSUIT_PARTS, rel=2, q="Требует проверки",
   note="Страна НЕ подтверждена: статья в русской ВикиФур не означает российскую прописку. Работоспособность домена не проверена."),

 L(cat="Private fursuit maker", name="Kin-ci", nick="kinciart", city="Нижний Новгород",
   reg="Нижегородская область", makes="Фурсьюты",
   proof="Статья в ВикиФур, VK-страница, профиль на форуме fursuit.ru",
   act="Не подтверждена (исторический профиль)", last="Подтверждённая активность ~2010-2012",
   how="VK", main="http://vk.com/kinciart", vk="http://vk.com/kinciart", tg="", ig="",
   site="http://kin-ci.furnation.ru/", email="", extra="",
   src="https://ru.wikifur.com/wiki/Kin-ci", src2="",
   why="Один из первых фурсьютеров Нижнего Новгорода; при сохранении деятельности — интересен для покрытия региона.",
   parts=FURSUIT_PARTS, rel=2, q="Требует проверки",
   note="Все подтверждения относятся к 2010-2012 гг. Профильный сайт на furnation.ru (площадка закрыта). Высокий риск неактивности."),
]

json.dump({"fursuit":fursuit,"cosplay":[],"unverified":unverified},
          open("leads_seed.json","w",encoding="utf-8"), ensure_ascii=False, indent=1)
print(f"seed: fursuit={len(fursuit)} unverified={len(unverified)}")
